# Generated by Django 5.1.6 on 2025-03-12 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothingitem',
            old_name='updated_app',
            new_name='updated_at',
        ),
    ]
